### ISSUE TITLE
Over flow error.

### ISSUE THREAD

**Issue by ProgrammerN** [chen-fishbein/stickyheaders-codenameone#1]
java.lang.StackOverflowError
    at sun.font.CCharToGlyphMapper$Cache.get(CCharToGlyphMapper.java:272)
    at sun.font.CCharToGlyphMapper.charsToGlyphs(CCharToGlyphMapper.java:147)
    at sun.font.CCharToGlyphMapper.charsToGlyphsNS(CCharToGlyphMapper.java:62)
    at sun.font.GlyphList.mapChars(GlyphList.java:269)
    at sun.font.GlyphList.setFromString(GlyphList.java:244)
    at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:71)
    at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
    at com.codename1.impl.javase.JavaSEPort.drawString(JavaSEPort.java:4098)
    at com.codename1.impl.CodenameOneImplementation.drawString(CodenameOneImplementation.java:6889)
    at com.codename1.impl.CodenameOneImplementation.drawLabelText(CodenameOneImplementation.java:6814)
    at com.codename1.impl.CodenameOneImplementation.drawLabelString(CodenameOneImplementation.java:6750)
    at com.codename1.impl.CodenameOneImplementation.drawLabelComponent(CodenameOneImplementation.java:6648)
    at com.codename1.ui.Label.paint(Label.java:471)
    at com.codename1.ui.Component.internalPaintImpl(Component.java:1314)
    at com.codename1.ui.Component.paintInternalImpl(Component.java:1288)
    at com.codename1.ui.Component.paintInternal(Component.java:1263)
    at com.codename1.ui.Container.paint(Container.java:1313)
    at com.otimotechnologies.demos.StickyHeader$1.paint(StickyHeader.java:119)
    at com.codename1.ui.Form.paintGlassImpl(Form.java:626)
    at com.codename1.ui.Component.paintGlassImpl(Component.java:1534)
    at com.codename1.ui.Container.paintGlassImpl(Container.java:1341)
    at com.codename1.ui.Component.paintGlassImpl(Component.java:1534)
    at com.codename1.ui.Container.paintGlassImpl(Container.java:1341)
    at com.codename1.ui.Container.paint(Container.java:1324)

**Comment by chen-fishbein** [comment]
The StickyHeader must stay in the com.codename1.ui package, it is explicitly overriding the paintGlassImpl method to do nothing to avoid this err.
Move it the the above package and it will start working for you
